# Generated by Django 5.1.1 on 2024-09-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='dataFim',
            field=models.DateTimeField(null=True, verbose_name='data fim publicada!'),
        ),
    ]
