# Generated by Django 5.1.1 on 2024-09-06 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controleApp', '0002_alter_prescricao_datafim'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controleApp.paciente'),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='controleApp.paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='prescricao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='controleApp.prescricao'),
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='dataInicio',
            field=models.DateTimeField(null=True, verbose_name='data inicío publicada!'),
        ),
    ]
