# Generated by Django 5.1.2 on 2024-10-10 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('dosagem', models.CharField(max_length=50)),
                ('forma', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateTimeField(verbose_name='Data de inicío')),
                ('dataFim', models.DateTimeField(verbose_name='Data de término')),
                ('frequenciaUso', models.CharField(max_length=200)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horarioPrescrito', models.DateTimeField(verbose_name='Horário prescrito')),
                ('horarioIngerido', models.DateTimeField(blank=True, null=True, verbose_name='horário ingerido')),
                ('observacao', models.CharField(blank=True, max_length=200, null=True)),
                ('prescricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.prescricao')),
            ],
        ),
    ]
