# Generated by Django 5.1.3 on 2024-11-08 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.CharField(max_length=10)),
                ('data_fim', models.CharField(max_length=10)),
                ('objetivos', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao_execucao', models.TextField()),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.treino')),
            ],
        ),
    ]
