# Generated by Django 5.1.3 on 2024-11-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_exercicio_treino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treino',
            old_name='objetivos',
            new_name='objetivo',
        ),
    ]
