# Generated by Django 5.1.3 on 2024-11-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_objetivos_treino_objetivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treino',
            name='objetivo',
            field=models.CharField(max_length=50),
        ),
    ]
