# Generated by Django 5.0.3 on 2024-10-13 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tag_livro_livro_tags_alter_autor_biografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='arquivo_pdf',
            field=models.CharField(max_length=50),
        ),
    ]
